<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>../Pinny.WpfBaseline/Assets/Pinny.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Baseline/NoteState.cs" Link="NoteState.cs" />
    <Compile Include="../Baseline/NoteStorage.cs" Link="NoteStorage.cs" />
  </ItemGroup>
</Project>
